import type { GraphV1 } from '../schema/graph-v1.js';
import { escapeHtml } from './shared.js';

export function renderSvg(graph:GraphV1):string{
  const visible=graph.nodes.filter((n)=>n.kind!=='run').slice(0,12);const width=Math.max(760,visible.length*196+48);const height=visible.length?330:300;
  const first=graph.firstBreak;const nodes=visible.map((n,i)=>{const x=28+i*196;const broken=first?.nodeId===n.id;return `<g transform="translate(${x} 128)" role="group" aria-label="${escapeHtml(`${n.kind} sequence ${n.sourceSeq}, ${n.status}`)}"><rect width="168" height="92" rx="10" fill="#141516" stroke="${broken?'#d97706':n.synthetic?'#62666d':'#34343a'}" stroke-width="${broken?3:1}" ${n.synthetic?'stroke-dasharray="6 5"':''}/><text x="14" y="24" fill="#8a8f98" font-size="11" font-family="ui-monospace,monospace">SEQ ${n.sourceSeq} · ${escapeHtml(n.kind.replace('rpc_',''))}</text><text x="14" y="49" fill="#f7f8f8" font-size="13" font-family="ui-monospace,monospace">${escapeHtml((n.method??n.toolName??n.id).slice(0,20))}</text><text x="14" y="74" fill="${broken?'#f59e0b':n.status==='ok'?'#27a644':'#d0d6e0'}" font-size="12" font-family="system-ui,sans-serif">${broken?'⚠ FIRST BREAK · ':''}${escapeHtml(n.status.toUpperCase())}</text></g>`}).join('');
  const connectors=visible.slice(1).map((_,i)=>`<path d="M ${28+i*196+168} 174 H ${28+(i+1)*196}" stroke="#3e3e44" stroke-width="1" stroke-dasharray="3 5" marker-end="url(#arrow)"/>`).join('');
  const empty=!visible.length?`<g transform="translate(48 126)"><rect width="664" height="108" rx="12" fill="#141516" stroke="#34343a"/><text x="24" y="42" fill="#f7f8f8" font-size="18" font-family="system-ui,sans-serif">No JSON-RPC exchanges found</text><text x="24" y="73" fill="#8a8f98" font-size="13" font-family="ui-monospace,monospace">causalwire record -- &lt;server command&gt;</text></g>`:'';
  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="cw-title cw-desc"><title id="cw-title">Causalwire evidence for ${escapeHtml(graph.run.id)}</title><desc id="cw-desc">${first?`First causal break ${escapeHtml(first.diagnosticCode)} at source sequence ${first.sourceSeq}.`:'No causal break detected.'} Metadata-only MCP causal graph.</desc><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#62666d"/></marker></defs><rect width="100%" height="100%" fill="#010102"/><text x="28" y="42" fill="#f7f8f8" font-size="24" font-weight="600" font-family="system-ui,sans-serif">CAUSALWIRE / CAUSAL EVIDENCE</text><text x="28" y="70" fill="#8a8f98" font-size="12" font-family="ui-monospace,monospace">${escapeHtml(graph.run.id)} · ${graph.run.captureComplete?'COMPLETE':'INCOMPLETE'} · CONTENT ${graph.run.contentPolicy.toUpperCase()} · ${escapeHtml(graph.mapping.id)}</text><line x1="28" y1="96" x2="${width-28}" y2="96" stroke="#23252a"/>${connectors}${nodes}${empty}<text x="28" y="${height-26}" fill="#62666d" font-size="11" font-family="system-ui,sans-serif">Metadata only · Hashes are not redaction · Generated locally</text></svg>`;
}
