#!/usr/bin/env node
import { Command, CommanderError, InvalidArgumentError } from 'commander';
import { constants, existsSync, lstatSync, mkdirSync, openSync, writeFileSync, closeSync, renameSync, unlinkSync } from 'node:fs';
import { basename, dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyzeJournal } from './normalize/pipeline.js';
import { recordChild } from './capture/child-process-wrapper.js';
import { renderCli } from './render/cli.js';
import { renderHtml } from './render/html.js';
import { renderSvg } from './render/svg.js';
import { mapOtlp, toOtlp } from './export/otlp.js';
import { writeUsageEvent } from './usage/local-usage-log.js';

const VERSION='0.1.0';
function duration(value:string):number{const match=/^(\d+(?:\.\d+)?)(ms|s|m)$/.exec(value);if(!match)throw new InvalidArgumentError('Use a duration such as 500ms, 30s, or 2m.');return Number(match[1])*(match[2]==='ms'?1:match[2]==='s'?1000:60_000);}
function bytes(value:string):number{const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new InvalidArgumentError('Expected a positive byte count.');return n;}
function positiveNumber(value:string):number{const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new InvalidArgumentError('Expected a positive finite number.');return n;}
function atomicWrite(path:string,data:string,overwrite=false):number{mkdirSync(dirname(path),{recursive:true,mode:0o700});const flags=constants.O_CREAT|constants.O_EXCL|constants.O_WRONLY|constants.O_NOFOLLOW;if(!overwrite){let fd:number|undefined;let created=false;try{fd=openSync(path,flags,0o600);created=true;writeFileSync(fd,data);closeSync(fd);fd=undefined;return Buffer.byteLength(data);}catch(error:any){if(fd!==undefined)closeSync(fd);if(created)try{unlinkSync(path)}catch{/* retain original error */}throw Object.assign(new Error(error?.code==='EEXIST'||error?.code==='ELOOP'?`Output already exists or is a symlink: ${path}`:`Unable to write output (${String(error?.code??'write_error')})`),{exitCode:74,cause:error});}}try{if(existsSync(path)&&lstatSync(path).isSymbolicLink())throw Object.assign(new Error(`Refusing symlink output: ${path}`),{exitCode:74});}catch(error:any){if(error.code!=='ENOENT')throw error;}const temp=join(dirname(path),`.${basename(path)}.${process.pid}.${Date.now()}.tmp`);let fd:number|undefined;try{fd=openSync(temp,flags,0o600);writeFileSync(fd,data);closeSync(fd);fd=undefined;renameSync(temp,path);return Buffer.byteLength(data);}catch(error:any){if(fd!==undefined)closeSync(fd);try{unlinkSync(temp)}catch{/* temp never existed */}throw Object.assign(new Error(`Unable to write output (${String(error?.code??'write_error')})`),{exitCode:74,cause:error});}}
const program=new Command();
program.name('causalwire').description('Local flight recorder for MCP stdio. Runs child commands with your user privileges; it is not a sandbox.').version(VERSION).option('--color <mode>','color: auto|always|never','auto').option('--quiet','suppress causalwire status, never child stderr').option('--usage-log <path>','write an opt-in local usage log; never uploaded').showHelpAfterError().exitOverride();

program.command('demo').description('Analyze a bundled seeded MCP failure; no network or backend required.').option('--scenario <name>','stuck-tool|orphan-result|duplicate-id','stuck-tool').option('--out-dir <dir>','artifact directory','.causalwire/demo').option('--format <format>','cli|html|svg|all','all').action(async(opts)=>{
  if(!['stuck-tool','orphan-result','duplicate-id'].includes(opts.scenario))throw Object.assign(new Error(`Unknown scenario: ${opts.scenario}`),{exitCode:64});if(!['cli','html','svg','all'].includes(opts.format))throw Object.assign(new Error(`Unknown format: ${opts.format}`),{exitCode:64});
  const global=program.opts();const start=Date.now();if(process.stderr.isTTY&&!global.quiet)process.stderr.write('Analyzing seeded failure…\n');const root=fileURLToPath(new URL('../fixtures/demo/',import.meta.url));const fixture=join(root,`${opts.scenario}.jsonl`);const graph=await analyzeJournal(fixture);
  if(opts.format==='cli'||opts.format==='all')process.stdout.write(renderCli(graph));
  const written:string[]=[];if(opts.format==='html'||opts.format==='all'){const path=join(opts.outDir,`${opts.scenario}.html`);atomicWrite(path,renderHtml(graph),true);written.push(path);}if(opts.format==='svg'||opts.format==='all'){const path=join(opts.outDir,`${opts.scenario}.svg`);atomicWrite(path,renderSvg(graph),true);written.push(path);}if(!global.quiet&&written.length)process.stderr.write(`Artifacts: ${written.join(', ')}\n`);writeUsageEvent(global.usageLog,'demo_completed',{version:VERSION,scenario:opts.scenario,duration_bucket:Date.now()-start<10_000?'under_10s':'10s_plus',success:true});
});

program.command('record').description('Transparently proxy and record an MCP stdio child process. Content is off by default.').option('--out <path>','exclusive journal output').option('--content <mode>','off|full','off').option('--protocol-version <version>').option('--request-timeout <duration>','live stuck timeout',duration,30_000).option('--max-frame-bytes <bytes>','frame bound',bytes,16*1024*1024).option('--max-journal-mb <MiB>','journal bound',positiveNumber,512).argument('<child...>','executable and arguments after --').allowUnknownOption().action(async(child:string[],opts)=>{
  if(!child.length)throw Object.assign(new Error('Missing child command. Use: causalwire record -- <server command>'),{exitCode:64});if(!['off','full'].includes(opts.content))throw Object.assign(new Error('Content must be off or full.'),{exitCode:64});if(opts.protocolVersion&&String(opts.protocolVersion).length>128)throw Object.assign(new Error('Protocol version must be 128 characters or fewer.'),{exitCode:64});const maxJournalBytes=opts.maxJournalMb*1024*1024;if(!Number.isSafeInteger(maxJournalBytes))throw Object.assign(new Error('Journal size is outside the supported range.'),{exitCode:64});const global=program.opts();if(opts.content==='full')process.stderr.write('WARNING: full content stores exact MCP frame bytes. Review before sharing; causalwire does not redact them.\n');
  const result=await recordChild({command:child[0],args:child.slice(1),out:opts.out,content:opts.content,protocolVersion:opts.protocolVersion,requestTimeoutMs:opts.requestTimeout,maxFrameBytes:opts.maxFrameBytes,maxJournalBytes,quiet:global.quiet,errorOutput:process.stderr});writeUsageEvent(global.usageLog,'capture_completed',{duration_bucket:result.durationMs<10_000?'under_10s':'10s_plus',frame_count_bucket:result.frameCount?'1_plus':'0',exchange_count_bucket:result.exchangeCount?'1_plus':'0',capture_complete:result.captureComplete,child_success:result.exitCode===0});process.exitCode=result.exitCode;
});

program.command('inspect').description('Normalize and diagnose a JournalV1 file.').argument('<journal>').option('--mapping <id>','mapping pack','mcp-jsonrpc@1').option('--request-timeout <duration>','stuck timeout',duration,30_000).option('--format <format>','summary|dag|json','summary').option('--fail-on <level>','none|warning|error','none').action(async(journal,opts)=>{
  if(!['summary','dag','json'].includes(opts.format)||!['none','warning','error'].includes(opts.failOn))throw Object.assign(new Error('Invalid inspect format or fail-on threshold.'),{exitCode:64});const start=Date.now();const graph=await analyzeJournal(journal,{mapping:opts.mapping,requestTimeoutMs:opts.requestTimeout});process.stdout.write(renderCli(graph,opts.format));const global=program.opts();writeUsageEvent(global.usageLog,'analysis_completed',{frame_count_bucket:graph.nodes.length>1?'1_plus':'0',first_break_code:graph.firstBreak?.diagnosticCode??'none',duration_bucket:Date.now()-start<10_000?'under_10s':'10s_plus'});if(opts.failOn!=='none'&&graph.diagnostics.some((d)=>opts.failOn==='warning'||d.severity==='error'))process.exitCode=1;
});

program.command('export').description('Export the same GraphV1 as HTML, SVG, OTLP, or offline OTLP JSON.').argument('<journal>').requiredOption('--format <format>','html|svg|otlp|otlp-json').option('--out <path>').option('--mapping <id>','mapping pack','mcp-jsonrpc@1').option('--service-name <name>','OTLP service name').action(async(journal,opts)=>{
  if(!['html','svg','otlp','otlp-json'].includes(opts.format))throw Object.assign(new Error(`Unknown export format: ${opts.format}`),{exitCode:64});const graph=await analyzeJournal(journal,{mapping:opts.mapping});let count=0;if(opts.format==='html'||opts.format==='svg'){const out=opts.out??`${journal.slice(0,extname(journal).length?-extname(journal).length:undefined)}.${opts.format}`;const data=opts.format==='html'?renderHtml(graph):renderSvg(graph);count=atomicWrite(out,data);if(!program.opts().quiet)process.stderr.write(`Wrote ${out} (${count} bytes)\n`);}else if(opts.format==='otlp-json'){const data=`${JSON.stringify(mapOtlp(graph,opts.serviceName),null,2)}\n`;if(opts.out){count=atomicWrite(opts.out,data);if(!program.opts().quiet)process.stderr.write(`Wrote ${opts.out} (${count} bytes)\n`);}else process.stdout.write(data);}else{const tracesEndpoint=process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT;const endpoint=tracesEndpoint??process.env.OTEL_EXPORTER_OTLP_ENDPOINT;const headers=Object.fromEntries((process.env.OTEL_EXPORTER_OTLP_HEADERS??'').split(',').filter(Boolean).map((item)=>{const at=item.indexOf('=');return at<0?[item,'']:[item.slice(0,at),item.slice(at+1)];}));const result=await toOtlp(graph,{endpoint,endpointIsTracesUrl:Boolean(tracesEndpoint),headers,serviceName:opts.serviceName,timeoutMillis:Number(process.env.OTEL_EXPORTER_OTLP_TIMEOUT??10_000)});if(!program.opts().quiet)process.stderr.write(result.spans?`Sent ${result.spans} spans / ${result.events} events / ${result.links} links\n`:'Nothing to export\n');count=result.spans;}writeUsageEvent(program.opts().usageLog,'export_completed',{format:opts.format,count_bucket:count?'1_plus':'0',success:true,error_class:'none'});
});

program.parseAsync(process.argv).catch((error:any)=>{if(error instanceof CommanderError){if(error.code==='commander.helpDisplayed'||error.code==='commander.version')return;process.exitCode=64;return;}const code=Number(error.exitCode??(/journal/i.test(String(error.message))||error.code==='ENOENT'?2:70));process.stderr.write(`causalwire: ${String(error.message??'Unexpected error')}\n`);if(process.env.DEBUG?.startsWith('causalwire:'))process.stderr.write(`${error.stack}\n`);process.exitCode=code;});
